In [28]:
import numpy as np
import pandas as pd
import os

In [29]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [30]:
df = pd.read_csv(data)

In [31]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [44]:
df_copy = df[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year', 'fuel_efficiency_mpg']].copy()

In [45]:
missing_values = df_copy.isnull().sum()

In [46]:
print(missing_values)

engine_displacement      0
horsepower             708
vehicle_weight           0
model_year               0
fuel_efficiency_mpg      0
dtype: int64

In [52]:
total_horsepower = df['horsepower'].sum()
total_horsepower_rows = df['horsepower'].count()
avg = total_horsepower/total_horsepower_rows
print(avg)

149.65729212983547

In [53]:
df['horsepower'].median()

149.0

# Prepare and split the dataset
#### 1. Shuffle the dataset (the filtered one you created above), use seed 42.
#### 2. Split your data in train/val/test sets, with 60%/20%/20% distribution.

In [59]:
n = len(df)

# do this to split
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

# test length
n, n_val + n_test + n_train

(9704, 9704)

In [60]:
df_val = df.iloc[:n_val]
df_test = df.iloc[n_val:n_val+n_test]
df_train = df.iloc[n_val+n_test:]

In [62]:
# create index
idx = np.arange(n)
#declare a seed to make randomisation repeatable
np.random.seed(42)
# shuffle
np.random.shuffle(idx)
print(idx)

[ 483 7506 8795 ... 5390  860 7270]

In [63]:
#get rows for split sets via shuffled index

df_val = df.iloc[idx[:n_val]]
df_test = df.iloc[idx[n_val:n_val+n_test]]
df_train = df.iloc[idx[:n_train]]

len(df_train), len(df_val), len(df_test),

(5824, 1940, 1940)

In [64]:
#test for randomness
df_train

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
483,220,3.0,144.0,2535.887591,18.7,2009,USA,Gasoline,All-wheel drive,2.0,16.642943
7506,160,2.0,141.0,2741.170484,14.3,2019,Asia,Diesel,Front-wheel drive,2.0,16.298377
8795,230,3.0,155.0,2471.880237,NaN,2017,Asia,Diesel,Front-wheel drive,2.0,18.591822
1688,150,3.0,206.0,3748.164469,15.5,2015,USA,Gasoline,All-wheel drive,1.0,11.818843
6217,300,4.0,111.0,2135.716359,16.9,2006,USA,Gasoline,All-wheel drive,NaN,19.402209
...,...,...,...,...,...,...,...,...,...,...,...
1696,260,5.0,139.0,2606.972984,15.9,2009,USA,Gasoline,All-wheel drive,-1.0,16.964054
5685,280,4.0,132.0,4004.214323,12.8,2014,Europe,Diesel,Front-wheel drive,2.0,10.059094
6735,210,3.0,152.0,2500.175687,16.4,2020,Europe,Gasoline,Front-wheel drive,0.0,17.593237
2052,250,6.0,154.0,2254.313245,13.3,2002,Asia,Gasoline,Front-wheel drive,2.0,18.925748
1776,210,11.0,152.0,2435.203606,14.7,2004,Europe,Diesel,Front-wheel drive,-1.0,17.965284

In [65]:
# remove index
df_train.reset_index(drop=True)
df_val.reset_index(drop=True)
df_test.reset_index(drop=True)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,110,2.0,144.0,2915.183706,13.2,2013,USA,Gasoline,All-wheel drive,-1.0,15.346002
1,200,2.0,105.0,2850.760653,11.5,2008,USA,Gasoline,Front-wheel drive,2.0,16.294345
2,180,5.0,125.0,3824.871931,15.6,2010,Asia,Diesel,All-wheel drive,1.0,10.643505
3,260,2.0,160.0,2651.797255,14.6,2018,USA,Diesel,All-wheel drive,2.0,16.908809
4,210,2.0,131.0,3003.607759,17.1,2018,USA,Gasoline,Front-wheel drive,-1.0,14.551272
...,...,...,...,...,...,...,...,...,...,...,...
1935,120,NaN,175.0,3079.478438,11.7,2007,Europe,Gasoline,All-wheel drive,NaN,14.773141
1936,220,2.0,NaN,2084.202686,13.0,2005,USA,Diesel,All-wheel drive,0.0,19.919012
1937,150,4.0,225.0,3038.900738,15.7,2019,USA,Diesel,All-wheel drive,-1.0,15.316219
1938,200,3.0,142.0,2807.085768,15.0,2017,Asia,Diesel,Front-wheel drive,1.0,15.937746
1939,230,7.0,145.0,3083.900680,17.1,2014,USA,Gasoline,Front-wheel drive,0.0,13.733984

# Question 3#### 
We need to deal with missing values for the column from Q1 
We have two options: fill it with 0 or with the mean of this variabl

#### .
Try both options. For each, train a linear regression model without regularization using the code from the lesso s.
For computing the mean, use the training on
#### ly!
Use the validation dataset to evaluate the models and compare the RMSE of each op ion.
Round the RMSE scores to 2 decimal digits using round(sco e, 2)
Which option gives better RMSE?

In [ ]:
Question 4
Now let's train a regularized linear regression.
For this question, fill the NAs with 0.
Try different values of r from this list: [0, 0.01, 0.1, 1, 5, 10, 100].
Use RMSE to evaluate the model on the validation dataset.
Round the RMSE scores to 2 decimal digits.
Which r gives the best RMSE?
If multiple options give the same best RMSE, select the smallest r.

In [ ]:
Question 5
We used seed 42 for splitting the data. Let's find out how selecting the seed influences our score.
Try different seed values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
For each seed, do the train/validation/test split with 60%/20%/20% distribution.
Fill the missing values with 0 and train a model without regularization.
For each seed, evaluate the model on the validation dataset and collect the RMSE scores.
What's the standard deviation of all the scores? To compute the standard deviation, use np.std.
Round the result to 3 decimal digits (round(std, 3))

In [ ]:
Question 6
Split the dataset like previously, use seed 9.
Combine train and validation datasets.
Fill the missing values with 0 and train a model with r=0.001.
What's the RMSE on the test dataset?

In [ ]:
Question 6
Split the dataset like previously, use seed 9.
Combine train and validation datasets.
Fill the missing values with 0 and train a model with r=0.001.
What's the RMSE on the test dataset?

In [ ]:
https://courses.datatalks.club/ml-zoomcamp-2025/homework/hw02